Remove %n in front and back of string
adamlc/address-format pull request #24
Opened 2024-09-15 21:36 UTC by jmslbam

So if `RECIPIENT` or `ORGANIZATION` are not filled or empty, then this results in only a `STREET_ADDRESS` that's prefix with an `%n` which will be replace by a `<br>` which results in an address that's starts a line lower then needed.

Fixes #23

2024-09-16 08:57 UTC, adamlc approved these changes

2024-09-16 08:58 UTC, adamlc requested changes
Thanks for your PR!

It looks like the tests are now failing. Would you mind updating them please?

2024-09-16 09:38 UTC, jmslbam commented
@adamlc, Ah yes I see that now. As it's not related to the scope of this issue, shall I update them in a different branch so those can be merged first before proceding with this PR's.

> The following actions use a deprecated Node.js version and will be forced to run on node20: actions/checkout@v3, actions/cache@v3. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/

Looks like we be needing `actions/checkout@v4`.

2024-09-17 10:26 UTC, adamlc commented
I'll be honest I haven't used this library or php for years, but it looks like the unit test is actually broken.

```
1) FormatTest::testDeAddressFormat
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
 'Eberhard Wellhausen\n
 Wittekindshof\n
 Schulstrasse 4\n
-32547 Oyenhause'
+32547 Oyenhausen'
```

The final `n` is being trimmed off the address, which could mean that it is related to this change.

2025-01-10 13:50 UTC, adamlc requested changes

2025-01-10 13:50 UTC, adamlc commented on tests/FormatTest.php
> +	);
Just a small niggle to fix the ident, otherwise test looks good I think!

2025-01-10 23:11 UTC, jmslbam commented on tests/FormatTest.php
> +	);
Like this? On 1 line? Because I copied it from the test about and just removed the `Eberhard Wellhausen\nWittekindshof\n`

2025-01-13 08:08 UTC, adamlc commented on tests/FormatTest.php
> +	);
@jmslbam sorry I meant indentation, you can see from the diff above it just needs bumping right

2025-01-13 11:01 UTC, jmslbam commented on tests/FormatTest.php
> +	);
Hmmz, which line exactly? Because in the div/panel of the PR makes it so that the lines visually jump to a new line. If you just view the file by itself / raw I don't see any issues with the new Code/Test

Can you screenshot / point which line it is?

https://github.com/adamlc/address-format/blob/b042c814a366d76e68615c57f706886048acd779/tests/FormatTest.php

![hmmz](https://github.com/user-attachments/assets/2fb365c2-9a2b-445a-9ede-d467a115fa33)

## To much indention
What I do see it that the other test have an extra indention which should be there from any kind of coding standard. I added a screenshot.

![indention](https://github.com/user-attachments/assets/861eb2c1-ceaa-4c66-b375-968042a25ce8)


![indention-2](https://github.com/user-attachments/assets/b922f916-574c-4965-adaf-85916e055cdb)

Thank you for taking the time and I can fix the overal indention in a new PR, no problemo

2025-01-13 11:03 UTC, adamlc commented on tests/FormatTest.php
> +	);
I'm just looking in my browser at the github pull request

![image](https://github.com/user-attachments/assets/74c89ae0-3751-4975-bb13-dd08111b6e8d)

2025-01-13 14:35 UTC, jmslbam commented on tests/FormatTest.php
> +	);
Ok I changed the tabs to spaces, will fix the other spacing / indention issues in a different PR and will add a `.editorconfig` to the repo which defines the settings for this project (spaces).

The FormatTest.php file mixes tabs and spaces as indentions.

Or if you ok, I can fix it in this same PR, save you time.

2025-01-13 14:49 UTC, adamlc commented on tests/FormatTest.php
> +	);
Feel free to add it into this PR. Greatly appreciated @jmslbam. The issues must have slipped through the net over the years and I've not noticed!

2025-01-13 20:33 UTC, jmslbam commented on tests/FormatTest.php
> +	);
Done 👍

2025-01-14 08:28 UTC, adamlc approved these changes

2025-01-14 08:28 UTC, merged

2025-01-14 08:28 UTC, adamlc commented
Amazing thanks for all your work @jmslbam

2025-01-14 12:59 UTC, jmslbam commented
@adamlc you're welcome! Thank you for the initial work of the package!